SEPRET/Models/Nature.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nature()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public bool Active { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}

SEPRET/Controllers/NatureController.cs
using SEPRET.CustomClasses;
using SEPRET.Models;
using SEPRET.Models.Custom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SEPRET.Controllers
{
    public class NatureController : Controller
    {
        // GET: Nature
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(NatureVM modelo)
        {
            using (SEPRETEntities DBC = new SEPRETEntities())
            {
                if (modelo.Id > 0)
                {
                    Nature Nature = DBC.Natures.FirstOrDefault(x => x.Id == modelo.Id);

                    Nature.Nombre = modelo.Nombre;
                    Nature.TimeUpdated = DateTime.Now;

                    DBC.SaveChanges();
                }
                else
                {
                    Nature Nature = new Nature
                    {
                        Nombre = modelo.Nombre,
                        Active = true,
                        TimeCreated = DateTime.Now
                    };

                    DBC.Natures.Add(Nature);
                    DBC.SaveChanges();
                }

                return View();
            }
        }

        [HttpPost]
        public ActionResult AddEdit(long Id)
        {
            using (SEPRETEntities DBC = new SEPRETEntities())
            {
                NatureVM modelo = new NatureVM();

                if (Id > 0)
                {
                    Nature Nature = DBC.Natures.FirstOrDefault(x => x.Id == Id);

                    modelo.Id = Nature.Id;
                    modelo.Nombre = Nature.Nombre;
                }

                return PartialView("~/Views/Nature/_AddEdit.cshtml", modelo);
            }
        }

        [HttpPost]
        public JsonResult UpdateStatus(long Id)
        {
            using (SEPRETEntities DBC = new SEPRETEntities())
            {
                Nature Nature = DBC.Natures.FirstOrDefault(x => x.Id == Id);

                if (Nature.Active)
                {
                    Nature.Active = false;
                }
                else
                {
                    Nature.Active = true;
                }

                Nature.TimeUpdated = DateTime.Now;

                DBC.SaveChanges();

                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult DT(DataTablesParameters param, string Filter)
        {
            using (SEPRETEntities DBC = new SEPRETEntities())
            {
                IEnumerable<Nature> Nature = Enumerable.Empty<Nature>();

                switch (Filter)
                {
                    case "Active":
                        Nature = DBC.Natures.Where(x => x.Active == true).ToList();
                        break;
                    case "Inactive":
                        Nature = DBC.Natures.Where(x => x.Active == false).ToList();
                        break;
                    default:
                        break;
                }

                long total = Nature.Count();

                #region Búsqueda
                string keyword = param.search.value;

                if (!string.IsNullOrEmpty(keyword))
                {
                    keyword = keyword.ToLower();

                    Nature = Nature.Where(x => x.Nombre.ToLower().Contains(keyword) ||
                    x.TimeCreated.ToString().ToLower().Contains(keyword));
                }

                long totalFiltered = Nature.Count();
                #endregion

                #region Ordenamiento
                int columnId = param.order[0].column;

                Func<Nature, string> orderFunction = (x => columnId == 0 ? x.Nombre : x.TimeCreated.ToString());

                if (param.order[0].dir == "asc")
                {
                    Nature = Nature.OrderBy(orderFunction);
                }
                else
                {
                    Nature = Nature.OrderByDescending(orderFunction);
                }
                #endregion

                #region Paginado
                Nature.Skip(param.start).Take(param.length);
                #endregion

                #region DataTable
                List<NatureVM> data = Nature.Select(x => new NatureVM
                {
                    Id = x.Id,
                    Nombre = x.Nombre,
                    TimeCreatedFormatted = x.TimeCreated.ToString(),
                    Active = x.Active
                }).ToList();
                #endregion

                return Json(new
                {
                    aaData = data,
                    param.draw,
                    iTotalRecords = total,
                    iTotalDisplayRecords = totalFiltered
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SEPRET/Views/Nature/Index.cshtml
@{
    ViewBag.Title = "View";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary card-header-icon row">
                <div class="card-icon">
                    <i class="material-icons">category</i>
                </div>
                <h4 class="card-title">Catálogo de carácter de proyecto</h4>
            </div>
            <div class="card-body">
                <div class="toolbar">
                    <!--        Here you can write extra buttons/actions for the toolbar              -->
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            <ul class="nav nav-pills nav-pills-rose mb-3" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active filter" data-toggle="tab" role="tablist" onclick="DT('Active');" style="cursor: pointer;">
                                        Activos
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link filter" data-toggle="tab" role="tablist" onclick="DT('Inactive');" style="cursor: pointer;">
                                        Inactivos
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-sm-12 text-right">
                            <button class="btn btn-round btn-sm btn-outline-primary" onclick="AddEdit(0);">
                                <i class="material-icons">add</i> Agregar un tipo de carácter
                            </button>
                        </div>
                    </div>
                </div>
                <div class="material-datatables" style="display: none;">
                    <div id="datatables_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="col-sm-12">
                            <table id="DT" class="table table-striped table-no-bordered table-hover dataTable dtr-inline" width="100%">
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Creado el</th>
                                        <th>Activo</th>
                                        <th>Editar</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Creado el</th>
                                        <th>Activo</th>
                                        <th>Editar</th>
                                    </tr>
                                </tfoot>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end content-->
        </div>
        <!--  end card  -->
    </div>
    <!-- end col-md-12 -->
</div>

<div class="modal fade" id="AddEditModal" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="card card-signup card-plain">
                <div class="modal-header">
                    <div class="card-header card-header-primary text-center">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            <i class="material-icons">clear</i>
                        </button>

                        <h4 class="card-title">Nombre del tipo de carácter</h4>
                    </div>
                </div>
                <div class="modal-body">
                </div>
            </div>
            <div class="card-footer text-center">
                <button class="btn btn-primary btn-round" onclick="Save();">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(() => {
            DT('Active');
        })

        Save = () => {
            let formData = new FormData(document.getElementById('Form'));

            fetch('@Url.Action("Index", "Nature")', {
                method: 'POST',
                body: formData
            })
                .then(response => {
                    if (response.ok) {
                        Table.draw();
                        $('#AddEditModal').modal('hide');
                        Site.OkNotification('El tipo de carácter se guardó exitosamente');
                    } else {
                        Site.ErrorNotification();
                    }
                })
                .catch(error => console.error(error))
        }

        AddEdit = Id => {
            fetch('@Url.Action("AddEdit", "Nature")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json;'
                },
                body: JSON.stringify({Id: Id})
            })
                .then(response => response.text())
                .then(data => {
                    $('.modal-body').html(data);
                    $('#AddEditModal').modal('show');
                })
                .catch(error => console.error(error))
        }

        UpdateStatus = Id => {
            fetch("@Url.Action("UpdateStatus", "Nature")", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json; charset=UTF-8'
                },
                body: JSON.stringify({ Id: Id })
            })
                .then(response => {
                    if (response.ok) {
                        Site.OkNotification('El estado del registro se actualizó correctamente');
                    } else {
                        Site.ErrorNotification();
                    }
                })
                .catch(error => console.error(error))
        }

        DT = Filter => {
            Table = $('#DT').DataTable({
                destroy: true,
                responsive: true,
                autoWidth: true,
                processing: true,
                serverSide: true,
                ajax: {
                    type: 'POST',
                    url: '@Url.Action("DT", "Nature")',
                    data: data => {
                        data.Filter = Filter
                    }
                },
                columns: [
                    { data: 'Nombre' },
                    { data: 'TimeCreatedFormatted' },
                    {
                        render: (data, type, row) => {
                            if (row['Active']) {
                                return '<div class="togglebutton"><label><input type="checkbox" checked="" onClick="UpdateStatus(' + row['Id'] + ');"><span class="toggle"></span></label></div>';
                            }
                            else {
                                return '<div class="togglebutton"><label><input type="checkbox" onClick="UpdateStatus(' + row['Id'] + ');"><span class="toggle"></span></label></div>';
                            }
                        }
                    },
                    {
                        data: 'Id',
                        render: (Id, type, full, meta) => '<button class="btn btn-round btn-outline-primary btn-fab btn-fab-mini" onClick="AddEdit(' + Id + ');"><i class="material-icons">edit</i></button>'
                    }
                ],
                columnDefs: [
                    { className: 'text-center', targets: [2, 3] }
                ],
                language: {
                    url: '@(HttpContext.Current.Request.Url.AbsolutePath.Contains("SEPRET") ? "/SEPRET/Assets/json/SpanishDT.json" : "/Assets/json/SpanishDT.json")'
                },
                initComplete: () => {
                    $('select').selectpicker();
                    Site.StyleDropdownDT();
                    $('.material-datatables').show();
                }
            })
        }
    </script>
} 

SEPRET/Views/Nature/_AddEdit.cshtml
@model SEPRET.Models.Custom.NatureVM

<div class="card-body">
    <form id="Form">

        <div class="form-group bmd-form-group" style="display: none;">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="material-icons">vpn_key</i></div>
                </div>
                <label class="bmd-label-floating prepend-label-margin">Id</label>
                @Html.TextBoxFor(x => x.Id, new { @class = "form-control", @type = "text" })
            </div>
        </div>

        <div class="form-group bmd-form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="material-icons">category</i></div>
                </div>
                <label class="bmd-label-floating prepend-label-margin">Nombre</label>
                @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control", @type = "text" })
            </div>
        </div>

    </form>
</div>